- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/tasks.md
- .github/ISSUE_TEMPLATE/user-story--dod-review.md
- .github/ISSUE_TEMPLATE/user_story.md
- .github/PULL_REQUEST_TEMPLATE.md
- added github templates from Helium
Closes #19
> added github templates

- Dockerfile
- pom.xml
- src/main/java/com/microsoft/azure/helium/app/VersionController.java
- src/main/java/com/microsoft/azure/helium/config/BuildConfig.java
Adds the /version endpoint 
Closes #23
> Version api

- src/main/java/com/microsoft/azure/helium/app/CustomErrorController.java
- src/main/java/com/microsoft/azure/helium/config/SwaggerConfig.java
- src/main/resources/application.properties
Remove default white labelling 404 response by spring
Closes #22
> handling-404-response

- src/main/java/com/microsoft/azure/helium/app/HealthzController.java
- src/main/java/com/microsoft/azure/helium/app/movie/MoviesService.java
- src/main/java/com/microsoft/azure/helium/config/RepositoryConfig.java
Added Retry configurations to match to C# version.
RequestTimeout = 60s, MaxRetryAttemptsOnRateLimitedRequests = 9, MaxRetryWaitTimeOnRateLimitedRequests = 60s
Closes #21
> Cosmos with retry option

- src/main/java/com/microsoft/azure/helium/app/HealthzController.java
- src/main/java/com/microsoft/azure/helium/app/movie/MoviesService.java
- src/main/java/com/microsoft/azure/helium/config/RepositoryConfig.java
- src/main/java/com/microsoft/azure/helium/health/ietf/IeTfStatus.java
Currently the health check response for success/failure/warn is up/down/warn , as per IeTF spec these values are changed to pass/fail/warn
References https://github.com/retaildevcrews/helium/issues/185
> ietf status - pass fail warn

- src/main/java/com/microsoft/azure/helium/app/HealthzController.java
Fixing 3 bugs
Return overall status warn if any status is "warn"
getTopRatedMovies (missing an s)
Affected endpoints should be an array - [ "/api/movies?toprated=true" ]
> ietf-bug-fixes

- src/main/java/com/microsoft/azure/helium/app/HealthzController.java
> remove extra duration parameter

- README.md
- updated az cosmosdb command to comply with latest az cli
- fixed a few formatting concerns that were spilling non-code text into bash blocks
- [ x] Documentation changes
- Closes #203 (this will automatically close the issue when the PR closes)
- References 212<issue number> (this references the issue but does not close with PR)
> Updated cosmosdb creation command

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/checkpoint.md
- .github/ISSUE_TEMPLATE/designreview.md
- .github/ISSUE_TEMPLATE/dod-review.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/release.md
- .github/ISSUE_TEMPLATE/retro.md
- .github/ISSUE_TEMPLATE/survey.md
- .github/ISSUE_TEMPLATE/task.md
- .github/ISSUE_TEMPLATE/user-story.md
- [ X] GitHub Template changes
Syncing github templates to helium
- References #226
> syncing issue template from helium

- src/main/java/com/microsoft/azure/helium/app/movie/MoviesService.java
MoviesService.java is throwing an exception. Adding null checks to query and genres
- Closes #61
> adding query null check to movies api

- .github/ISSUE_TEMPLATE/designreview.md
Updating template to populate in issue template list
- References https://github.com/retaildevcrews/helium/issues/240
> Java -Design Template update

- .gitignore
- pom.xml
- src/main/java/com/microsoft/cse/helium/app/config/BuildConfig.java
- src/main/java/com/microsoft/cse/helium/app/config/SwaggerConfig.java
- src/main/java/com/microsoft/cse/helium/app/controllers/SecretController.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/IKeyVaultService.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultService.java
- src/main/resources/application.properties
- src/test/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultServiceTest.java
This PR adds:
*   /healthz endpoint using the health actuator
*   adds application.properties back to the files 
*   removes the application.properties from .gitignore
*   moves some string literals to static finals
*   matches secret name used with C# MIKV
*   fixed format of pom
*   fixed data format in BuildConfig used to report in version controller
*   added getter for KeyVaultService on SecretController to support later test creation
*   added a create factory method for KeyVaultService to support test creation
- References #65  (this references the issue but does not close with PR)
> Jofultz mikv

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/release.md
- .github/ISSUE_TEMPLATE/task.md
Per design review feedback yesterday, updated template descriptions and templates.
Changes made:
- Bug Template - Description and consolidated "Additional Content"
- Tasks Template - Description and removed "if applicable" to reference 
- Release Template - Added "Validate e2e testing" in release checklist
- DoD Template - Added Next Steps section to "create release template"
- Feature Request - Added Next Steps section
Additional Template changes are Lint related - no major changes.
- References https://github.com/retaildevcrews/helium/issues/235
> Updated Standard Templates (Bug, Task, Release, DoD, Feature)

- .github/ISSUE_TEMPLATE/dod-review.md
- .github/ISSUE_TEMPLATE/feature.md
Per design review feedback yesterday, updated template descriptions and templates.
Changes made:
- DoD Template - Added Next Steps section to "create release template"
- Feature Request - Added Next Steps section
Additional Template changes are Lint related - no major changes.
- Closes https://github.com/retaildevcrews/helium/issues/235
> Updated Standard Templates (DoD, Feature)

- .github/workflows/dockerByPR.tmp
- .github/workflows/dockerCI.tmp
…t README.md
- [X ] CI-CD changes
quick bug fix to ignore all .md file changes. No effect as CI is turned off
> update ignore paths to ignore all changes to .md files instead of README

- src/main/java/com/microsoft/cse/helium/app/controllers/SecretController.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/IKeyVaultService.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultService.java
- src/test/java/com/microsoft/cse/helium/app/controllers/VersionControllerTest.java
This PR corrects the signatures and calling semantics for the class methods to make call path completely async.
- Closes #88
> Refactor to mono

- src/main/java/com/microsoft/cse/helium/app/controllers/RobotsController.java
- src/main/resources/static/robots.txt
Added a handler for robots.txt.  It will handle requests for [base URL]/robots[*].txt.  I also removed the previous static resource for robots.  
- Closes #67
> add handler for robots and removed static file

- pom.xml
- src/main/java/com/microsoft/cse/helium/app/config/CosmosDbConfig.java
- src/main/java/com/microsoft/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/resources/application.properties
- src/test/resources/application.properties
To remove autoconfigure setup from the framework
- Closes #104
> Rem autocofigure

- src/main/java/com/microsoft/cse/helium/app/controllers/SecretController.java
- src/test/java/com/microsoft/cse/helium/app/controllers/SecretControllerTest.java
MIKV Unit Test Implementation for GetSecret
- Closes #65
> mikv unit-tests

- .gitignore
- Dockerfile
- pmdcheck.sh
- pom.xml
- src/main/java/com/microsoft/cse/helium/app/config/CosmosDbConfig.java
- src/main/java/com/microsoft/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/models/Actor.java
- src/main/java/com/microsoft/cse/helium/app/models/ActorBase.java
- src/main/java/com/microsoft/cse/helium/app/models/Movie.java
- src/main/java/com/microsoft/cse/helium/app/models/Role.java
- src/main/java/com/microsoft/cse/helium/app/services/configuration/ConfigurationService.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultService.java
- src/main/resources/application.properties
- src/test/java/com/microsoft/cse/helium/app/controllers/ActorControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/controllers/SecretControllerTest.java
CICD bug error caused a new PR.
Now we integrate PMD and FindBugs in Helium-Java
- Closes #116 (this will automatically close the issue when the PR closes)
> New PR for PMD and FindBug static code analysis

- src/main/java/com/microsoft/cse/helium/app/Constants.java
- src/main/java/com/microsoft/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/models/Actor.java
- src/main/java/com/microsoft/cse/helium/app/models/Movie.java
- src/main/java/com/microsoft/cse/helium/app/utils/CommonUtils.java
Querying actors by point query for 1 RU and low latency
- Closes #131
> single movie read

- src/main/java/com/microsoft/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/microsoft/cse/helium/app/controllers/MoviesController.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
- src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
Read Movie by MovieId
- Closes #136
> single movie read api

- src/main/java/com/microsoft/cse/helium/app/Constants.java
- src/main/java/com/microsoft/cse/helium/app/controllers/MoviesController.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
Fixing Bug #144 
Fixed MoviesController getAll. Added test to verify that "/movies" returns list of type Movie
- Closes #144
> Bug Fix #144 - MoviesController should pass Entity.Movie

- src/main/java/com/microsoft/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/microsoft/cse/helium/app/controllers/Controller.java
- src/main/java/com/microsoft/cse/helium/app/controllers/MoviesController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/BaseCosmosDbDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/IDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/controllers/VersionControllerTest.java
This PR refactors controllers and data access objects to a generic function, base type functionality, and an interface for the data access layer.  Benefits are:
* reduction of duplicate code
* removal of dao type knowledge from base controller object
* removal of unnecessary Enum 
* removed conditional previously needed to execute specific DAO
- Closes #142
> Generic for getAll refactor

- .gitignore
- pom.xml
- src/main/java/com/microsoft/cse/helium/app/Constants.java
- src/main/java/com/microsoft/cse/helium/app/HeliumJavaApplication.java
- src/main/java/com/microsoft/cse/helium/app/services/configuration/ConfigurationService.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/EnvironmentReader.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/IEnvironmentReader.java
- src/main/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultService.java
- src/main/resources/application.properties
- src/test/java/com/microsoft/cse/helium/app/HeliumJavaApplicationTests.java
- src/test/java/com/microsoft/cse/helium/app/controllers/ActorControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/controllers/GenreControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/controllers/SecretControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/controllers/VersionControllerTest.java
- src/test/java/com/microsoft/cse/helium/app/services/keyvault/KeyVaultServiceTest.java
Removed hard dependency on env variables via springboot and add CLI args
- Closes #122  (this will automatically close the issue when the PR closes)
> Use cli args

- src/main/java/com/microsoft/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/microsoft/cse/helium/app/controllers/Controller.java
- src/main/java/com/microsoft/cse/helium/app/controllers/MoviesController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/GenresDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/IDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
- src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
Implement Get all movies by year
- Closes #139
> Get all movies by year

- src/main/java/com/microsoft/cse/helium/app/controllers/Controller.java
- src/main/java/com/microsoft/cse/helium/app/controllers/MoviesController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/IDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
Filter by rating and actorid
- Closes #158 #160
> filter by rating and actorid

- src/main/java/com/microsoft/cse/helium/app/controllers/Controller.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/IDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
This changes Movies and Actors DAO to conform to a single getAll() call which takes a dictionary of query params.  This helps reduce duplicate code and helps create cleaner abstraction between controller and DAO.
- Closes #161
> Movies and Actor DAO getAll() Refactor

- src/main/java/com/microsoft/cse/helium/app/models/ActorBase.java
- src/main/java/com/microsoft/cse/helium/app/models/Role.java
- src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java
Updates to code base to correct issues serializing birthYear, deathYear, and roles when they were not in the source data.
- Closes #166 
- Closes #167 
- Closes #168
> Remediation for birthYear, deathYear, and roles response serialization

- Dockerfile
- pom.xml
- src/main/java/com/microsoft/cse/helium/app/config/BuildConfig.java
- src/main/java/com/microsoft/cse/helium/app/controllers/Controller.java
- src/main/java/com/microsoft/cse/helium/app/controllers/RobotsController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/GenresDao.java
- src/main/java/com/microsoft/cse/helium/app/dao/MoviesDao.java
- src/main/java/com/microsoft/cse/helium/app/utils/ParameterValidator.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
Implementation on genre filter on movie API
- Closes #157
> Filter by genre

- src/main/java/com/microsoft/cse/helium/app/dao/GenresDao.java
- src/test/java/com/microsoft/cse/helium/app/controllers/MovieControllerTest.java
Fixing the Genre=Action bug
- Closes #171
> fixing genre=Action bug

- .gitignore
- src/main/java/com/microsoft/cse/helium/app/controllers/IndexController.java
Redirect / to swagger-ui.html
- Closes #82  (this will automatically close the issue when the PR closes)
> Swagger redirect

- Dockerfile
Pulling in the app insights jar file into the docker image so we have telemetry as the new app insights jar file does a "codeless attach"
- References #164  (this references the issue but does not close with PR)
> Add appinsights to helium-java

- src/main/java/com/microsoft/cse/helium/app/Constants.java
- src/main/java/com/microsoft/cse/helium/app/controllers/HealthzController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/health/ietf/IeTfStatus.java
- src/main/resources/application.properties
- src/test/java/com/microsoft/cse/helium/app/controllers/HealthzControllerTest.java
- src/test/resources/application.properties
This PR adds the health and healthz/ietf endpoints to the codebase.  
I ran the code base against WebV with bad.json, baseline.json, and benchmark.json and passed all tests.
- Closes #177
> Add healthz and healthz/ietf

- .github/ISSUE_TEMPLATE/release.md
Updated Release template with "to do code" & dependencies checkbox
- References #https://github.com/retaildevcrews/helium/issues/323
> Update Release template

- src/main/java/com/microsoft/cse/helium/app/Constants.java
- src/main/java/com/microsoft/cse/helium/app/controllers/HealthzController.java
- src/main/java/com/microsoft/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/microsoft/cse/helium/app/health/ietf/IeTfStatus.java
- src/main/resources/application.properties
- src/test/java/com/microsoft/cse/helium/app/controllers/HealthzControllerTest.java
- src/test/resources/application.properties
Merging code back in after much testing and no root cause found and no errors found.
- Closes #200
> healthz code re-merge

- Dockerfile
- src/main/resources/application.properties
- src/test/resources/application.properties
Updating the port to helium-java app 4120
- Closes #181
> updated port to 4120

- pom.xml
- src/main/java/com/cse/helium/app/controllers/SecretController.java
- src/main/java/com/cse/helium/app/services/keyvault/IKeyVaultService.java
- src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
- src/main/java/com/cse/helium/app/utils/CommonUtils.java
- src/main/resources/application.properties
This update changes the SDK version used
- Closes #162 
- References: https://github.com/retaildevcrews/helium/issues/195
> Identity and KeyVault SDK Updates

- .github/workflows/dockerCI.yml
- Dockerfile
- Dockerfile-Dev
Modify the dockerfile to remove references to HOME env variable and 
- Closes #48  (this will automatically close the issue when the PR closes)
> Adding the Docker dev file

- src/main/java/com/cse/helium/app/services/keyvault/EnvironmentReader.java
- src/main/java/com/cse/helium/app/utils/CommonUtils.java
minimal change to trigger ci/cd
> Jofultz silentfail

- src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
Temporary fix to set KV client log level to NONE.
- References #226
> Set log level to NONE for KV client

- src/main/java/com/cse/helium/app/utils/CommonUtils.java
Fix the help command to take the long form as required by the helium standard
- Closes #224  (this will automatically close the issue when the PR closes)
> updating the help command to meet the helium standard

- src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
This adds the capability of mapping the assignment of the KeyVault logging level in accordance with the application logging level as detail in #226 
- Closes #226
> set kv logging in accordance with app logging

- src/main/java/com/cse/helium/app/services/configuration/ConfigurationService.java
- src/main/java/com/cse/helium/app/services/keyvault/IKeyVaultService.java
- src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
Removing suffixes as they are unnecessary.
- Closes #221
> Removed Suffixes from KeyVaultService Methods

- src/main/resources/static/swagger.json
update IETF portion of swagger
References retaildevcrews/helium#384
> swagger update

- src/main/java/com/cse/helium/app/Constants.java
- src/main/java/com/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/cse/helium/app/dao/BaseCosmosDbDao.java
- src/main/java/com/cse/helium/app/dao/GenresDao.java
- src/main/java/com/cse/helium/app/dao/MoviesDao.java
Sql Query Parameterization to protect against Sql Injection
- [ X] Unit tests updated and ran successfully
- Closes #207
> sql parameterization

- src/main/java/com/cse/helium/app/config/CosmosDbConfig.java
Updated consistency level for CosmosDB client.
- Closes #234
> updated ConsistencyLevel

- Dockerfile
- pom.xml
Remove the version number from docker file
- [ X] Unit tests updated and ran successfully
- Closes #209
> remove version number from Dockerfile

- src/main/java/com/cse/helium/app/controllers/IndexController.java
- src/main/java/com/cse/helium/app/services/keyvault/EnvironmentReader.java
Changed raw type to generic type to remove warnings.
- Closes #243
> added generic type for ResponseEntity<>

- pom.xml
- src/main/java/com/cse/helium/app/controllers/ActorsController.java
- src/main/java/com/cse/helium/app/controllers/MoviesController.java
- src/main/java/com/cse/helium/app/error/GlobalErrorWebExceptionHandler.java
Fixing #241 and #242 
- [ X] Unit tests updated and ran successfully
- Closes #241 and #242
> fix for #241 and #242

- src/main/java/com/cse/helium/app/error/GlobalErrorWebExceptionHandler.java
Fix linter error
- Closes #246
> linter error fix

- README.md
> cicd readme updates

- .devcontainer/devcontainer.json
- src/main/resources/log4j2.properties
- src/main/resources/logback.xml
Supress CosmosDB SDK Logs
- Closes #228
> Cosmosdb loglevel

- TestFiles/perfTargets.json
- TestFiles/perfTargets.txt
copying perfTargets.json to .txt
***PLEASE DO NOT Merge**.  WIll merge once WebV has been updated.
> perfTargets.json to .txt

- TestFiles/perfTargets.json
**remove perfTargets.json** once we have merged webV changes please.  Do not merge until WebV has been updated.
> remove perfTargets.json once we have merged webV changes please

- docs/vscode-template/launch.json
- docs/vscode-template/tasks.json
> added vscode template

- pom.xml
- src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
Modifies code to create specific credential types instead of disabling part of the default chain.
- Closes #266
> Identity SDK Update

- README.md
- docs/vscode-template/launch.json
- pom.xml
Simplifying usage with less commands
- Closes #268
> removing mvn clean package and moving env up in launch.json

- README.md
Updated ietf error message to readme
- Closes #271
> added ietf error msg to readme

- .github/workflows/dockerCI.yml
- added TestFiles/** to ci-cd ignore list
> added TestFiles to ignore

- .devcontainer/post-install.sh
- added docker completion file
- added bash-completion
- References retaildevcrews/helium#397
> added bash completion to install script

- pom.xml
- src/main/java/com/cse/helium/app/middleware/RequestLogger.java
#Type of PR
Add web request logging for helium java
- Closes #211
> Request logging Middleware

- src/main/java/com/cse/helium/app/HeliumJavaApplication.java
Fix deprecated swagger annotations
- Closes #282
> Updated annontation

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/post-install.sh
- Dockerfile
- pom.xml
Upgrade Java version to 11, and use a custom docker image for Codespaces.
- Closes #287 (this will automatically close the issue when the PR closes)
> Upgrade to Java SDK 11

- src/main/java/com/cse/helium/app/controllers/VersionController.java
Ensure consistency between /version endpoints in helium repositories. apiVersion to be shown before appVersion.
- References https://github.com/retaildevcrews/helium/issues/466
> Version Endpoint Consistency with other Helium Repos

- saveenv.sh
- src/main/java/com/cse/helium/app/Constants.java
- src/main/java/com/cse/helium/app/services/keyvault/EnvironmentReader.java
- src/main/java/com/cse/helium/app/services/keyvault/KeyVaultService.java
- src/main/java/com/cse/helium/app/utils/CommonUtils.java
- src/test/java/com/cse/helium/app/services/keyvault/KeyVaultServiceTest.java
- src/test/resources/application.properties
Since MSI has been since replaced with the newer term MI, updating any references in the code to avoid any confusion.
- References https://github.com/retaildevcrews/helium/issues/501
> Renaming MSI references to MI

- pom.xml
- src/test/java/com/cse/helium/app/controllers/ActorControllerTest.java
- src/test/java/com/cse/helium/app/controllers/MovieControllerTest.java
- src/test/java/com/cse/helium/app/controllers/VersionControllerTest.java
This should resolve the Netty issue as Netty remediation was included in the version of the CosmosDB SDK that this PR switches the code to us.
I also resolved a couple of linter and test issues.
- Closes #202 
- Closes #253
> Update CosmosDB SDK

- .devcontainer/Dockerfile
- .devcontainer/post-install.sh
To Include .NET Core and WebValidate to Codespaces custom Docker image.
- Closes #291
> Added .NET Core and WebValidate to custom Codespaces Dockerfile

- .devcontainer/.bashrc-append
- .devcontainer/Dockerfile
Fix issue of webvalidate not working properly.
> Fixed issue for webvalidate in custom Dockerfile

- .devcontainer/Dockerfile
- .github/workflows/codespaces.yml
- .github/workflows/dockerCI.yml
To add CICD for the custom codespaces Dockerfile
- Closes #289 (this will automatically close the issue when the PR closes)
> Codespaces docker

- pom.xml
- src/main/java/com/cse/helium/app/error/GlobalErrorWebExceptionHandler.java
- src/main/resources/application.properties
When the app is terminated, ensure that the existing connections will be processed by the server (up to 20s) and any new connections will be dropped (graceful shutdown).
- References https://github.com/retaildevcrews/helium/issues/383
> Drain connections + graceful shutdown

- src/main/resources/static/swagger/helium.json
Updated min and max length values for q parameter search in Swagger UI
- References #retaildevcrews/helium/issues/525
> Updated min and max length values for q parameter

- README.md
Updated bash run instructions in README.md to include environment variables needed. Added a line to set the environment variable KEYVAULT_NAME.
- Closes #300
> Updated README.md to set env variables for bash runs

- README.md
- pom.xml
- src/test/java/com/cse/helium/app/controllers/ActorControllerTest.java
- src/test/java/com/cse/helium/app/controllers/FeaturedMovieControllerTest.java
- src/test/java/com/cse/helium/app/controllers/GenreControllerTest.java
- src/test/java/com/cse/helium/app/controllers/HealthzControllerTest.java
- src/test/java/com/cse/helium/app/controllers/MovieControllerTest.java
- src/test/java/com/cse/helium/app/controllers/SecretControllerTest.java
- src/test/java/com/cse/helium/app/controllers/VersionControllerTest.java
Update testing framework to JUnit5, as well as other package updates.
- Closes #304
> Pom upgrades

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/checkpoint.md
- .github/ISSUE_TEMPLATE/comparison.md
- .github/ISSUE_TEMPLATE/designreview.md
- .github/ISSUE_TEMPLATE/dod-review.md
- .github/ISSUE_TEMPLATE/feature.md
- .github/ISSUE_TEMPLATE/issue.md
- .github/ISSUE_TEMPLATE/release.md
- .github/ISSUE_TEMPLATE/retro.md
- .github/ISSUE_TEMPLATE/survey.md
- .github/ISSUE_TEMPLATE/task.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/dockerCI.yml
Updating ci-cd to avoid build on PR merges and changing up the GH templates.
Also some master to main changes.
- References https://github.com/retaildevcrews/helium/issues/488
> Updating ci-cd and GH templates, master to main changes

- src/main/java/com/cse/helium/app/dao/ActorsDao.java
- src/main/java/com/cse/helium/app/dao/MoviesDao.java
- src/main/java/com/cse/helium/app/models/Actor.java
- src/main/java/com/cse/helium/app/models/Movie.java
Changing name of partitionKeyFunction to something clearer.
- References https://github.com/retaildevcrews/helium/issues/537
> Renaming partition key method

- .github/ISSUE_TEMPLATE/found-dead-links.md
- .github/workflows/mdlinkcheck.yml
- .github/workflows/scheduled_mdlinkcheck.yml
Added scheduled link checks for markdown files to CI. Link checks will run once a week
- References https://github.com/retaildevcrews/helium/issues/542
> Added scheduled checks to CI

- pom.xml
Updating the outdated java packages to prepare for the next release of helium-java.
- Closes #313
> Package and SDK version updates

- README.md
- SECURITY.md
Adding the Security doc file here to keep the documentation consistent between all helium language repos.
- References https://github.com/retaildevcrews/helium/issues/581
> Sync root docs with other Helium repos

- .devcontainer/Dockerfile
- .github/workflows/codespaces.yml
Push the java devcontainer Dockerfile on a recurring schedule for package updates.
- Closes #318
> Scheduled push for devcontainer image

- src/main/java/com/cse/helium/app/utils/ParameterValidator.java
- src/main/resources/static/swagger/helium.json
Fix the year to 2025 for movie year validation
> Fixed the year validation to 2025
